# Generated by Django 2.2.6 on 2019-10-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191008_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryID',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='productID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='specifications',
            old_name='productID',
            new_name='product',
        ),
    ]
