# Generated by Django 2.2.6 on 2019-10-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_images_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='Image',
            field=models.FileField(upload_to='Images/'),
        ),
    ]
